---
- name: Install nginx
  apt: name=nginx state=present
  sudo: true
  tags: install

- name: Remove the default config
  file: state=absent path=/etc/nginx/sites-enabled/default
  sudo: true
  ignore_errors: true
  tags: install

- name: Stat the SSL Certificate
  stat: path=../templates/server.crt
  register: cert
  tags: install

- name: Copy the SSL Certificate
  copy: src=../templates/server.crt dest=/etc/nginx/server.crt
  sudo: true
  tags: install
  when: cert.stat.exists == true

- name: Copy the SSL Key
  copy: src=../templates/server.key dest=/etc/nginx/server.key
  sudo: true
  tags: install
  when: cert.stat.exists == true

- name: Copy nginx configuration
  template: src=pari.conf dest=/etc/nginx/sites-enabled/pari.conf
  sudo: true
  ignore_errors: true
  tags: install

- name: Restart nginx
  service: name=nginx state=restarted
  sudo: true
  tags: install
