[production]
ruralindiaonline.org

[qa]
54.255.193.26

[local]
127.0.0.1

[vagrant]
development.ruralindiaonline.org

[vagrant:vars]
base_path=/vagrant
app_path=/vagrant
requirements_file="/vagrant/requirements.dev.txt"
settings_path="pari.settings.dev"