---
- name: Ensure apt is up to date
  apt: update_cache=yes
  sudo: true
  tags: install

- name: Ensure packages are upgraded
  apt: upgrade=full
  sudo: true
  tags: install

- name: Ensure the following packages are installed
  apt: name={{ item }}
  with_items:
    - python-dev
    - python-pip
    - python-virtualenv
    - libjpeg-dev
    - libfreetype6-dev
    - libtiff5-dev
    - zlib1g-dev
    - git
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - supervisor
    - openjdk-7-jre-headless
    - redis-server
  sudo: true
  tags: install

- name: Install redis python library
  pip: name=redis
  sudo: true
  tags: install

- name: Download node.js LTS
  get_url: url=https://nodejs.org/dist/v4.2.4/node-v4.2.4.tar.gz dest={{ base_path }}

- name: Uncompress the node.js LTS package
  unarchive: src=node-v4.2.4.tar.gz dest={{ base_path }} copy=no

- name: Configure node.js LTS
  command: chdir={{ base_path }}/node-v4.2.4 ./configure

- name: Compile node.js LTS
  command: chdir={{ base_path }}/node-v4.2.4 make

- name: Install node.js LTS
  command: chdir={{ base_path }}/node-v4.2.4 make install
  sudo: true

- name: Install lessc
  npm: name=less global=yes
  sudo: true
