---
- name: Download node.js LTS
  get_url: url=https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}.tar.gz dest={{ base_path }}

- name: Uncompress the node.js LTS package
  unarchive: src={{ base_path }}/node-v{{ node_version }}.tar.gz dest={{ base_path }} copy=no

- name: Configure node.js LTS
  command: chdir={{ base_path }}/node-v{{ node_version }} ./configure

- name: Compile node.js LTS
  command: chdir={{ base_path }}/node-v{{ node_version }} make

- name: Install node.js LTS
  command: chdir={{ base_path }}/node-v{{ node_version }} make install
  become: true
  become_method: sudo