---
- name: Download elasticsearch
  get_url: >
    url=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.0.deb
    dest=/tmp/elasticsearch.deb
  sudo: true
  tags: install

- name: Install elasticsearch
  apt: deb=/tmp/elasticsearch.deb
  sudo: true
  tags: install

- name: Restart elasticsearch
  service: name=elasticsearch state=restarted
  sudo: true
  tags: install
