---
- name: Install postgres
  apt: name={{ item }}
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  sudo: true
  tags: install

- name: Create a db user
  postgresql_user: name={{ db_user }} password={{ db_password }}
  sudo: true
  sudo_user: postgres
  tags: install

- name: Create a db
  postgresql_db: name={{ db_name }} owner={{ db_user }}
  sudo: true
  sudo_user: postgres
  tags: install
